part of 'product_details_bloc.dart';

class ProductDetailsState extends Equatable {
  const ProductDetailsState({
    required this.product,
    required this.storeName,
    required this.storeLink,
    this.storeId,
    this.isOwnStore = false,
    this.initialImageIndex = 0,
    this.galleryFeed,
    this.galleryFeedIndex = 0,
    this.isLoadingPhotos = false,
    this.revision = 1,
    this.apiTag = '',
    this.specifications,
    this.precisionTag = '',
    this.subGroups = const [],
    this.seedCategory = '',
    this.showStoreGroupLink = false,
    this.canEdit = false,
    this.canDelete = false,
    this.shouldOpenEdit = false,
    this.isDeleting = false,
    this.isDeleted = false,
    this.infoMessage,
  });

  final StoreProduct product;
  final String storeName;
  final String storeLink;
  final String? storeId;
  final bool isOwnStore;
  final int initialImageIndex;

  /// When opened from store gallery: swipe across all photos (all groups/dates).
  final List<ProductDetailsFeedItem>? galleryFeed;
  final int galleryFeedIndex;

  final bool isLoadingPhotos;
  final int revision;
  final String apiTag;
  final ProductSpec? specifications;
  final String precisionTag;
  final List<CollectionSubGroup> subGroups;

  /// Optional category from search (or other seed) until detail specs load.
  final String seedCategory;

  /// Search entry: chevron beside store name opens that store's product group.
  final bool showStoreGroupLink;
  final bool canEdit;
  final bool canDelete;
  final bool shouldOpenEdit;
  final bool isDeleting;
  final bool isDeleted;
  final String? infoMessage;

  bool get hasGalleryFeed =>
      galleryFeed != null && galleryFeed!.isNotEmpty;

  /// Display title for the photo at [imageIndex]: collection name for main and
  /// auto-named Precise/Standalone clusters; custom sub-group name otherwise.
  PhotoTitleParts titlePartsForPhoto(int imageIndex) {
    final collectionName =
        product.title.trim().isEmpty ? 'Item' : product.title.trim();
    final photoId =
        imageIndex >= 0 && imageIndex < product.photoAssetIds.length
            ? product.photoAssetIds[imageIndex].trim()
            : '';

    if (photoId.isNotEmpty) {
      for (final sub in subGroups) {
        final inSub = sub.photos.any(
          (p) =>
              p.url.trim().isNotEmpty && (p.id?.trim() ?? '') == photoId,
        );
        if (!inSub) continue;
        final rawName = sub.name.trim();
        final base =
            rawName.isEmpty || isAutoGeneratedSubGroupName(rawName)
                ? collectionName
                : rawName;
        return PhotoTitleParts(title: base);
      }
    }

    return PhotoTitleParts(title: collectionName);
  }

  /// Category pill label for the photo (sub-group overrides group). Title-cased
  /// for display (e.g. `ring` → `Ring`, `bridal_set` → `Bridal Set`).
  String categoryLabelForPhoto(int imageIndex) {
    final raw = _categoryRawForPhoto(imageIndex);
    final source = raw.isNotEmpty ? raw : seedCategory.trim();
    if (source.isEmpty) return '';
    return _titleCaseCategory(source);
  }

  String _categoryRawForPhoto(int imageIndex) {
    final photoId =
        imageIndex >= 0 && imageIndex < product.photoAssetIds.length
            ? product.photoAssetIds[imageIndex].trim()
            : '';

    if (photoId.isNotEmpty) {
      for (final sub in subGroups) {
        final inSub = sub.photos.any((p) => (p.id?.trim() ?? '') == photoId);
        if (!inSub) continue;
        final subCat = sub.specifications?.category.trim() ?? '';
        if (subCat.isNotEmpty) return subCat;
      }
    }

    return specifications?.category.trim() ?? '';
  }

  static String _titleCaseCategory(String raw) {
    if (raw.isEmpty) return raw;
    return raw
        .split(RegExp(r'[_\s]+'))
        .where((p) => p.isNotEmpty)
        .map((p) {
          final lower = p.toLowerCase();
          return '${lower[0].toUpperCase()}${lower.substring(1)}';
        })
        .join(' ');
  }

  /// Specs chrome for the photo at [imageIndex] (sub-group Precise overrides group).
  /// Null when title-only (no weight line to show).
  PhotoSpecDisplay? specDisplayForPhoto(int imageIndex) {
    final photoId =
        imageIndex >= 0 && imageIndex < product.photoAssetIds.length
            ? product.photoAssetIds[imageIndex].trim()
            : '';

    if (photoId.isNotEmpty) {
      for (final sub in subGroups) {
        final inSub = sub.photos.any((p) => (p.id?.trim() ?? '') == photoId);
        if (!inSub) continue;
        final isStandalone = sub.name.toLowerCase().contains('standalone');
        final subSpec = ProductSpec.fromApiJson(sub.specifications?.toJson());
        final tag = sub.precisionTag.trim();
        final fromSpec = _chromeFromSpec(subSpec);
        if (fromSpec != null) return fromSpec;
        if (tag.isNotEmpty) {
          final fromTag = _chromeFromPrecisionTag(tag);
          if (fromTag != null) return fromTag;
        }
        if (isStandalone) return null;
        return const PhotoSpecDisplay(
          line: 'Precise details applied',
          primaryLabel: null,
          primaryValue: null,
        );
      }
    }

    final fromGroup = _chromeFromSpec(specifications);
    if (fromGroup != null) return fromGroup;

    final groupTag = precisionTag.trim();
    if (groupTag.isNotEmpty) {
      final fromTag = _chromeFromPrecisionTag(groupTag);
      if (fromTag != null) return fromTag;
    }

    return null;
  }

  static PhotoSpecDisplay? _chromeFromSpec(ProductSpec? spec) {
    if (spec == null) return null;
    final primary = spec.primaryWeightDisplay;
    final details = spec.weightDetailLines;
    if (primary == null && details.isEmpty) return null;
    final label = primary?.label;
    final value = primary?.value;
    final line =
        label != null && value != null ? '$label $value' : details.join(' | ');
    return PhotoSpecDisplay(
      line: line,
      primaryLabel: label,
      primaryValue: value,
      detailLines: details,
      fineWeightLine:
          label == 'Fine' && value != null ? 'Fine weight : $value' : null,
    );
  }

  /// Parse API / display precision tag into primary weight + expandable details.
  static PhotoSpecDisplay? _chromeFromPrecisionTag(String tag) {
    final display = _displayPrecisionTag(tag);
    final parts =
        display
            .split('|')
            .map((s) => s.trim())
            .where((s) => s.isNotEmpty)
            .toList();
    if (parts.isEmpty) return null;

    String? label;
    String? value;
    final details = <String>[];

    for (final part in parts) {
      final net = RegExp(
        r'^Net\s+(.+)$',
        caseSensitive: false,
      ).firstMatch(part);
      if (net != null) {
        label ??= 'Net';
        value ??= net.group(1)!.replaceAll(' ', '');
        continue;
      }
      final gross = RegExp(
        r'^Gross\s+(.+)$',
        caseSensitive: false,
      ).firstMatch(part);
      if (gross != null) {
        // Prefer Net if already found; otherwise use Gross as primary.
        if (label == null) {
          label = 'Gross';
          value = gross.group(1)!.replaceAll(' ', '');
        }
        continue;
      }
      // Purity-looking bare number (e.g. `92`).
      if (RegExp(r'^\d+(?:\.\d+)?$').hasMatch(part)) {
        details.add('Purity $part');
        continue;
      }
      // Wastage `2%`.
      if (RegExp(r'^\d+(?:\.\d+)?%$').hasMatch(part)) {
        details.add('Wastage $part');
        continue;
      }
      if (part.toLowerCase().contains('size') ||
          RegExp(r'^\d').hasMatch(part)) {
        details.add(
          part.toLowerCase().startsWith('size') ||
                  part.toLowerCase().contains('free')
              ? part
              : 'Size $part',
        );
        continue;
      }
      details.add(part);
    }

    if (label == null && value == null && details.isEmpty) return null;
    return PhotoSpecDisplay(
      line: display,
      primaryLabel: label,
      primaryValue: value,
      detailLines: details,
    );
  }

  /// API `precisionTag` → details chrome:
  /// `22K (92%) | 55g | 2% W | Free Size` → `92 | Gross 55g | 2% | Free Size`
  /// `22K (92%) | 25g (Net: 20g) | 1% W | Free Size` → `92 | Net 25g | 1% | Free Size`
  /// `22K (92%) | 10-20g | 1% W | Free Size` → `92 | Gross 10-20g | 1% | Free Size`
  static String _displayPrecisionTag(String tag) {
    final parts =
        tag
            .split('|')
            .map((s) => s.trim())
            .where((s) => s.isNotEmpty)
            .toList();
    if (parts.isEmpty) return tag.trim();

    final out = <String>[];
    for (var i = 0; i < parts.length; i++) {
      final part = parts[i];

      final karat = RegExp(
        r'^(\d+(?:\.\d+)?)K\s*\(([^)]+)\)\s*$',
        caseSensitive: false,
      ).firstMatch(part);
      if (karat != null) {
        out.add(_purityDisplay(karat.group(2)!));
        continue;
      }

      // Already-stripped purity like `92%` (first segment only).
      if (i == 0 && RegExp(r'^\d+(?:\.\d+)?%\s*$').hasMatch(part)) {
        out.add(_purityDisplay(part));
        continue;
      }

      final withNet = RegExp(
        r'^(\d+(?:\.\d+)?)\s*g\s*\(\s*Net:\s*[^)]+\)\s*$',
        caseSensitive: false,
      ).firstMatch(part);
      if (withNet != null) {
        out.add('Net ${withNet.group(1)}g');
        continue;
      }

      // Fixed `55g` or range `10-20g` / `10–20g`.
      final gross = RegExp(
        r'^(\d+(?:\.\d+)?(?:\s*[-–]\s*\d+(?:\.\d+)?)?)\s*g\s*$',
        caseSensitive: false,
      ).firstMatch(part);
      if (gross != null) {
        final weight = gross
            .group(1)!
            .replaceAll(RegExp(r'\s*[-–]\s*'), '-')
            .trim();
        out.add('Gross ${weight}g');
        continue;
      }

      final wastage = RegExp(
        r'^(\d+(?:\.\d+)?)\s*%\s*W\s*$',
        caseSensitive: false,
      ).firstMatch(part);
      if (wastage != null) {
        out.add('${wastage.group(1)}%');
        continue;
      }

      out.add(part);
    }
    return out.join(' | ');
  }

  static String _purityDisplay(String raw) {
    var value = raw.trim();
    if (value.endsWith('%')) {
      value = value.substring(0, value.length - 1).trim();
    }
    return value;
  }

  ProductDetailsState copyWith({
    StoreProduct? product,
    String? storeName,
    String? storeLink,
    String? storeId,
    bool? isOwnStore,
    int? initialImageIndex,
    List<ProductDetailsFeedItem>? galleryFeed,
    int? galleryFeedIndex,
    bool? isLoadingPhotos,
    int? revision,
    String? apiTag,
    ProductSpec? specifications,
    bool clearSpecifications = false,
    String? precisionTag,
    List<CollectionSubGroup>? subGroups,
    String? seedCategory,
    bool? showStoreGroupLink,
    bool? canEdit,
    bool? canDelete,
    bool? shouldOpenEdit,
    bool clearShouldOpenEdit = false,
    bool? isDeleting,
    bool? isDeleted,
    bool clearDeleted = false,
    String? infoMessage,
    bool clearInfoMessage = false,
  }) {
    return ProductDetailsState(
      product: product ?? this.product,
      storeName: storeName ?? this.storeName,
      storeLink: storeLink ?? this.storeLink,
      storeId: storeId ?? this.storeId,
      isOwnStore: isOwnStore ?? this.isOwnStore,
      initialImageIndex: initialImageIndex ?? this.initialImageIndex,
      galleryFeed: galleryFeed ?? this.galleryFeed,
      galleryFeedIndex: galleryFeedIndex ?? this.galleryFeedIndex,
      isLoadingPhotos: isLoadingPhotos ?? this.isLoadingPhotos,
      revision: revision ?? this.revision,
      apiTag: apiTag ?? this.apiTag,
      specifications:
          clearSpecifications
              ? null
              : (specifications ?? this.specifications),
      precisionTag: precisionTag ?? this.precisionTag,
      subGroups: subGroups ?? this.subGroups,
      seedCategory: seedCategory ?? this.seedCategory,
      showStoreGroupLink: showStoreGroupLink ?? this.showStoreGroupLink,
      canEdit: canEdit ?? this.canEdit,
      canDelete: canDelete ?? this.canDelete,
      shouldOpenEdit:
          clearShouldOpenEdit
              ? false
              : (shouldOpenEdit ?? this.shouldOpenEdit),
      isDeleting: isDeleting ?? this.isDeleting,
      isDeleted: clearDeleted ? false : (isDeleted ?? this.isDeleted),
      infoMessage: clearInfoMessage ? null : (infoMessage ?? this.infoMessage),
    );
  }

  @override
  List<Object?> get props => [
    product,
    storeName,
    storeLink,
    storeId,
    isOwnStore,
    initialImageIndex,
    galleryFeed,
    galleryFeedIndex,
    isLoadingPhotos,
    revision,
    apiTag,
    specifications,
    precisionTag,
    subGroups,
    seedCategory,
    showStoreGroupLink,
    canEdit,
    canDelete,
    shouldOpenEdit,
    isDeleting,
    isDeleted,
    infoMessage,
  ];
}

class PhotoSpecDisplay extends Equatable {
  const PhotoSpecDisplay({
    required this.line,
    this.label,
    this.fineWeightLine,
    this.primaryLabel,
    this.primaryValue,
    this.detailLines = const [],
  });

  final String line;
  final String? label;
  /// e.g. `Fine weight : 23.5g` when Fine is the primary (legacy).
  final String? fineWeightLine;

  /// `Fine` / `Net` / `Gross` — shown as the weight title.
  final String? primaryLabel;

  /// e.g. `78.35g` — shown muted beside the title.
  final String? primaryValue;

  /// Expandable rows: purity, wastage, size.
  final List<String> detailLines;

  bool get hasPrimaryWeight =>
      (primaryLabel?.trim().isNotEmpty ?? false) &&
      (primaryValue?.trim().isNotEmpty ?? false);

  @override
  List<Object?> get props => [
    line,
    label,
    fineWeightLine,
    primaryLabel,
    primaryValue,
    detailLines,
  ];
}

class PhotoTitleParts extends Equatable {
  const PhotoTitleParts({required this.title});

  final String title;

  @override
  List<Object?> get props => [title];
}
