/// Publish auto-names Precise/Standalone clusters as
/// `{collectionTitle} precise {n}` / `{collectionTitle} standalone {n}`.
/// Browse and product details hide those as section/photo titles (blue dot
/// already marks Precise); custom sub-group names still show.
bool isAutoGeneratedSubGroupName(String name) {
  final trimmed = name.trim();
  if (trimmed.isEmpty) return false;
  return RegExp(
    r'^.+\s+(precise|standalone)\s+\d+$',
    caseSensitive: false,
  ).hasMatch(trimmed);
}
